agmp_app/urls.py
from django.urls import path, re_path, include
# from django.conf.urls import url

from . import views
from .views import (DrugagmpDetailView, PhamacogeneDrugAssoc, VariantStudyagmpListView,VarDrugAssocDetailView,VvarDrugAssocDetailView,DiseaseVariantDetailView,VarDisAssocDetailView, PharmacoDrugDetailView,VariantDiseaseAssocDetailView,VariantDrugAssociationDetailView,search_view, test_data_table)

urlpatterns = [
    path('test', test_data_table, name='test_data_table'),
    path('', search_view, name='search_view'),
    path('about', views.about, name='about'),
#  old url for search   path('search_v', views.search_all, name='search_v'),  
    path('home', views.home, name='home'),
    #new views
    path('drug-detail/<int:pk>/', DrugagmpDetailView.as_view(), name='drug-detail'),
    path('variant-drug-list/<int:pk>/',VariantStudyagmpListView.as_view(), name='variant-drug-list'),
     ##### New URLS for data tables ######
    path('PhamacogeneDrugAssoc/<str:gene_id>/',
         PhamacogeneDrugAssoc.as_view(),
         name='PhamacogeneDrugAssoc'),

    path('VarDrugAssoc/<str:rs_id>/',
         VarDrugAssocDetailView.as_view(),
         name='Var_Drug_Assoc'),

    
    path('VariantDiseaseAssoc/<str:rs_id>/',
         VariantDiseaseAssocDetailView.as_view(),
         name='Variant_Disease_Assoc'),


    path('VvarDrugAssoc/<str:rs_id>/',
         VvarDrugAssocDetailView.as_view(),
         name='Vvar_Drug_Assoc'),

    path('VarDisAssoc/<str:rs_id>/',
         VarDisAssocDetailView.as_view(),
         name='Var_Dis_Assoc'),

    path('PharmacoDrug/<str:gene_id>/',
         PharmacoDrugDetailView.as_view(),
         name='Pharmaco_Drug_Detail'),

    path('VariantDrugAssociation/<str:drug_id>/',
         VariantDrugAssociationDetailView.as_view(),
         name='VariantDrugAssociation'),

     
    path('DiseaseVariant/<str:phenotypeagmp__name>/',
         DiseaseVariantDetailView.as_view(),
         name='DiseaseVariant'),

     ##### New URLS for data tables ######

    # call search query with optional parameters 
    path('summary/', views.summary, name='summary'),
    path('resources/', views.resources, name='resources'),
    path('outreach/', views.outreach, name='outreach'),
    path('contact/', views.contact, name='contact'),
    path('databases/', views.databases, name='databases'),
    path('tools_pipelines/', views.tools_pipelines, name='tools_pipelines'),
    path('online_courses/', views.online_courses, name='online_courses'),
    path('disclaimer', views.disclaimer, name='disclaimer'),
    path('faqs', views.faqs, name='faqs'),
    path('tutorial/', views.tutorial, name='tutorial'),
    path('help', views.help, name='help'),
    path('agnocomplete/', include('agnocomplete.urls')),
]

agmp_app/forms.py
from django import forms



class ModelSelectForm(forms.Form):
    MODELS = [
        ('product', 'Product'),
        # Add more models as needed
    ]

    model_choice = forms.ChoiceField(choices=MODELS, widget=forms.RadioSelect)
    search_query = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'id': 'autocomplete'}))





class SearchForm(forms.Form):
    SEARCH_CHOICES = (
        ('Variantagmp', 'Variant'),
        ('Geneagmp', 'Gene'),
        ('Drugagmp', 'Drug'),
        ('Disease', 'Disease'),
    )
    search_option = forms.ChoiceField(choices=SEARCH_CHOICES, widget=forms.RadioSelect,label="Choose a category to search by")
    search_query = forms.CharField(max_length=100)


class ModelSearchForm(forms.Form):


    MODELS_CHOICES = [
        ('variantagmp', 'Variant'),
        ('geneagmp', 'Gene'),
        ('drugagmp', 'Drug'),
        ('disease', 'Disease'),
    ]

    model_selection = forms.ChoiceField(choices=MODELS_CHOICES, widget=forms.RadioSelect,label="Choose a category to search by")
    search_query = forms.CharField(max_length=100, required=False, label="Search")

agmp_app/templates/DiseaseVariantDetail.html
 {% extends 'mainLayout.html' %} 
PhamacogeneDrugAssoc/CFH/


{% block title %} Variant Drug Associations {% endblock %}

{% block banner %}

{% include 'partials/banner_results.html' %}

{% endblock %}

{% block content %}
<!-- Initialize DataTables -->

{% comment %} <p>Gene: {{data.gene_id}}</p>

<p>Uniprot ID: <a href="https://www.uniprot.org/uniprotkb/{{data.uniprot_ac}}/entry" target="_blank">{{data.uniprot_ac}}</a></p>

<p>Function: {{data.function}} </p> {% endcomment %}


<p><h3>Variant-Phenotype Associations</h3></p>
<div class="table-responsive-sm">
  <table id="example01" class="table table-striped table-bordered"> 
      <thead>
          <tr>
              <th>Variant</th>
              <th>Gene</th>
              <th>Phenotype</th>
              <th>Significance</th>
              <th>Region</th>
              <th>Country of Participants</th>
              <th>Study</th>
          </tr>
      </thead>
      <tbody>
         {% for my_object in object_list_d %}
          <tr>
              <td>{{my_object.variantagmp.rs_id }}
              </td>
              <td><a href="/PhamacogeneDrugAssoc/{{my_object.variantagmp.geneagmp.gene_id }}">{{my_object.variantagmp.geneagmp.gene_id }}</a>
            
              </td>
              <td>{{my_object.variantagmp.phenotypeagmp.name }}<br></td>
              <td>{{my_object.p_value}}
              </td>
              <td>{{my_object.geographical_regions}}</td>
              <td>{{my_object.country_participant}}</td>
         <td><a href="https://pubmed.ncbi.nlm.nih.gov/{{my_object.studyagmp.publication_id}}">{{my_object.studyagmp.publication_id}}</a></td>
            
             
           
             
              
          </tr>

          {% empty %}

    

          {% endfor %}  
       
         
    
    
    
      </tbody>
    </table>
    
</div>
<!-- Include required CSS and JS files -->
 

<script type="text/javascript">


$(document).ready(function() {
    function initializeTable(tableId, columnSelectId) {
        var table = $(tableId).DataTable({
            dom: 'lBfrtip',
            buttons: [
                {
                    extend: 'collection',
                    text: 'Export',
                    buttons: [
                        {
                            extend: 'copy',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'excel',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'csv',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'pdf',
                            exportOptions: {
                                columns: ':visible'
                            }
                        }
                    ]
                },
                'colvis'
            ],
            columnDefs: [{
                targets: '_all',
                visible: true // Display all columns by default
            }]
        });

        // Create checkboxes for column selection
        table.columns().every(function(index) {
            var column = this;
            var checked = column.visible() ? 'checked' : '';
            var checkbox = $('<label><input type="checkbox" ' + checked + '>' + $(column.header()).text() + '</label>');

            // Handle checkbox click event
            checkbox.find('input').on('click', function() {
                var isChecked = this.checked;
                column.visible(isChecked);
            });

            $(columnSelectId).append(checkbox);
        });
    }

    initializeTable('#example01', '#columnSelect1');
    // initializeTable('#example3', '#columnSelect2');
});

 



 

</script>

{% endblock %}

agmp_app/templates/VariantDiseaseAssocDetail.html
 {% extends 'mainLayout.html' %} 
 {% load static %}
 <title>Data Table Example</title>


{% block title %} Variant Phenotype Associations {% endblock %}


{% block banner %}

{% include 'partials/banner_results.html' %}

{% endblock %}

{% block content %}
<!-- incomplete top labels-->


<h3> {{rs_id_display.rs_id}} </h3><hr>

<p><b>Variant ID: </b>{{rs_id_display.rs_id}}</p>

<p><b>Gene:</b> <a href="/PhamacogeneDrugAssoc/{{gene_name_display.geneagmp__gene_id}}">{{gene_name_display.geneagmp__gene_id}}</a></p>

<p><b>Chromosome:</b> {{chromosome_display.geneagmp__chromosome}} </p>

<p><h3>Variant-Phenotype Associations</h3></p>


  <div class="table-responsive-sm">
    <table id="example" class="table table-striped table-bordered">
      <thead>
          <tr>
              <th>Variant</th>
              <th>Gene</th>
              <th>Phenotype</th>
              <th>Significance</th>
              <th>Region</th>
              <th>Country</th>
              <th>Study</th>
              <th>Variant Type</th>
              <th>Source DB</th>
              <th>Mixed Population</th>
              <!-- <th>Study Type</th> -->
          </tr>
      </thead>
      <tbody>
     {% for my_object in object_list %}
          <tr>
              <td>{{my_object.variantagmp.rs_id}}</td>
              <td><a href="/PhamacogeneDrugAssoc/{{my_object.variantagmp.geneagmp.gene_id }}"> {{my_object.variantagmp.geneagmp.gene_id }}</a>
              <td>{{my_object.variantagmp.phenotypeagmp.name}}
                <td>{{my_object.p_value}}</td>
                <td>{{my_object.geographical_regions}}</td>
                <td>{{my_object.country_participant}}</td>
              <td><a href="https://pubmed.ncbi.nlm.nih.gov/{{my_object.studyagmp.publication_id}}">{{my_object.studyagmp.publication_id}}</a>
            </td>
            <td>{{my_object.variantagmp.variant_type }}</td>
            <td>{{my_object.variantagmp.source_db }}</td>
            <!-- <td>{{my_object.studyagmp.study_type}}</td> -->
            <td>{{my_object.mixed_population }}</td>
          </tr>


          {% empty %}
      

          {% endfor %}  
          <!-- ... more rows ... -->
      </tbody>
    </table>
    
    
 
    

</div>



<!-- Include required CSS and JS files -->
<script>
$(document).ready(function() {
 function initializeTable(tableId, columnSelectId) {
    var table = $(tableId).DataTable({
        dom: 'lBfrtip',
        buttons: [
            {
                extend: 'collection',
                text: 'Export',
                buttons: [
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        }
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        }
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        }
                    }
                ]
            },
            'colvis'
        ],
        columnDefs: [
            {
                targets: '_all',
                visible: true
            }
        ],
        initComplete: function(settings, json) {
            // Hide the last 3 columns
            var api = this.api();
            var columnsCount = api.columns().nodes().length;
            for (var i = 1; i <= 3; i++) {
                api.column(columnsCount - i).visible(false);
            }
        }
    });

    // Create checkboxes for column selection
    table.columns().every(function(index) {
        var column = this;
        var checked = column.visible() ? 'checked' : '';
        var checkbox = $('<label><input type="checkbox" ' + checked + '>' + $(column.header()).text() + '</label>');
        // Handle checkbox click event
        checkbox.find('input').on('click', function() {
            var isChecked = this.checked;
            column.visible(isChecked);
        });
        $(columnSelectId).append(checkbox);
    });
 }
 initializeTable('#example', '#columnSelect1');
 // initializeTable('#example3', '#columnSelect2');
});

</script>




{% endblock %}

agmp_app/templates/_databases.html
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" class="font-weight-normal">Name</th>
                <th scope="col" class="font-weight-normal">Description</th>

            </tr>
        </thead>
        <tbody>
            <tr>
                <td>

                    <a target="_blank" href="https://www.pharmgkb.org/">PharmGKB</a>
                </td>
                <td>The PharmGKB is a pharmacogenomics knowledge resource that
                    encompasses clinical information including clinical guidelines
                    and drug labels, potentially clinically actionable gene-drug
                    associations and genotype-phenotype relationships.
                </td>

            </tr>
            <tr>

                <td>
                    <a target="_blank" href="https://www.genome.jp/kegg/">KEGG</a>
                </td>
                <td>KEGG is a database resource for understanding high-level functions
                    and utilities of the biological system, such as the cell, the organism and
                    the ecosystem, from molecular-level information, especially large-scale
                    molecular datasets generated by genome sequencing and other high-throughput
                    experimental technologies.
                </td>

            </tr>
            <tr>

                <td>
                    <a target="_blank" href="https://www.ncbi.nlm.nih.gov/clinvar/">ClinVar</a>
                </td>
                <td>ClinVar aggregates information about genomic variation and its relationship to human health.
                </td>

            </tr>
            <tr>

                <td>
                    <a target="_blank" href="https://www.ncbi.nlm.nih.gov/snp">dbSNP</a>
                </td>
                <td>dbSNP contains human single nucleotide variations, microsatellites, and small-scale insertions and
                    deletions along with publication, population frequency, molecular consequence, and genomic and
                    RefSeq
                    mapping information for both common variations and clinical mutations.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://www.pharmvar.org/">PharmVar</a>
                </td>
                <td>The Pharmacogene Variation (PharmVar) Consortium is a central repository for pharmacogene (PGx)
                    variation that focuses on haplotype structure and allelic variation.</td>

            </tr>
            <tr>

                <td>
                    <a target="_blank" href="https://www.ebi.ac.uk/gwas/">GWAS Catalog</a>
                </td>
                <td>The GWAS Catalog provides a consistent, searchable, visualisable and freely available database of
                    published SNP-trait associations, which can be easily integrated with other resources, and is
                    accessed
                    by scientists, clinicians and other users worldwide.</td>

            </tr>
            <tr>

                <td>
                    <a target="_blank" href="https://www.omim.org/">OMIM</a>
                </td>
                <td>OMIM is a comprehensive, authoritative compendium of human genes and genetic phenotypes that is
                    freely
                    available and updated daily.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://genome.ucsc.edu/">UCSC</a>
                </td>
                <td>The UCSC Genome Browser is an on-line, and downloadable, genome browser hosted by the University of
                    California, Santa Cruz (UCSC).</td>

            </tr>
            <tr>


                <td>
                    <a target="_blank" href="https://www.uniprot.org/">UniProt</a>
                </td>
                <td>The mission of UniProt is to provide the scientific community with a comprehensive, high-quality and
                    freely accessible resource of protein sequence and functional information.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://www.genecards.org/">GeneCards</a>
                </td>
                <td>GeneCards is a searchable, integrative database that provides comprehensive, user-friendly
                    information
                    on all annotated and predicted human genes.</td>

            </tr>
            <tr>


                <td>
                    <a target="_blank" href="https://www.ensembl.org/index.html">Ensembl</a>
                </td>
                <td>Ensembl is a genome browser for vertebrate and invertebrate genomes that supports research in
                    comparative genomics, evolution, sequence variation and transcriptional regulation.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://www.ncbi.nlm.nih.gov/gene">NCBI Gene</a>
                </td>
                <td>NCBI Gene integrates information from a wide range of species. A record may include nomenclature,
                    Reference Sequences (RefSeqs), maps, pathways, variations, phenotypes, and links to genome-,
                    phenotype-,
                    and locus-specific resources worldwide.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://clinicalgenome.org/">ClinGen</a>
                </td>
                <td>ClinGen is a National Institutes of Health (NIH)-funded resource dedicated to building a central
                    resource that defines the clinical relevance of genes and variants for use in precision medicine and
                    research.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://monarchinitiative.org/">Monarch Initiative</a>
                </td>
                <td>The Monarch Initiative is a large scale bioinformatics web resource focused on leveraging existing
                    biomedical knowledge to connect genotypes with phenotypes in an effort to aid research that combats
                    genetic diseases.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="http://myvariant.info/">MESH</a>
                </td>
                <td>MeSH (Medical Subject Headings) is the NLM controlled vocabulary thesaurus used for indexing
                    articles
                    for PubMed.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://icd.who.int/en">ICD11</a>
                </td>
                <td>International Classification of Diseases 11th Revision. The global standard for diagnostic health
                    information.</td>

            </tr>
            <tr>

                <td>
                    <a target="_blank" href="https://gnomad.broadinstitute.org">gnomAD</a>
                </td>
                <td>The Genome Aggregation Database (gnomAD), is a coalition of investigators seeking to aggregate and
                    harmonize exome and genome sequencing data from a variety of large-scale sequencing projects, and to
                    make summary data available for the wider scientific community.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://cpicpgx.org/">CPIC</a>
                </td>
                <td>The Clinical Pharmacogenetics Implementation Consortium (CPIC®) is an international consortium of
                    individual volunteers and a small dedicated staff who are interested in facilitating the use of
                    pharmacogenetic tests for patient care.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://pubchem.ncbi.nlm.nih.gov/">PubChem</a>
                </td>
                <td>PubChem is the world's largest collection of freely accessible chemical information. Search
                    chemicals by
                    name, molecular formula, structure, and other identifiers.</td>

            </tr>
            <tr>
                <td>
                    <a target="_blank" href="https://www.drugbank.ca">Drug Bank</a>
                </td>
                <td>The DrugBank database is a unique bioinformatics and cheminformatics resource that combines detailed
                    drug data with comprehensive drug target information.</td>

            </tr>
            <tr>

                <td>
                    <a target="_blank" href="http://www.disgenet.org/">DisGeNET</a>
                </td>
                <td>DisGeNET is a discovery platform containing one of the largest publicly available collections of
                    genes
                    and variants associated to human diseases.</td>

            </tr>
    </table>
</div>

agmp_app/templates/graph 2.html
{% extends 'mainLayout.html' %}



{% block title%}Graph{% endblock %}


{% block banner %}


{% include 'partials/banner_about.html' %}

{% endblock %}





</script>

{% block content %}
<div id="container" style="width: 75%;">

</div>





<div class="row">
	<div class="col-md-3">
		<nav class="navigation" id="mainNav">

			<ul>
				<div class="no_style">

					<li><a class="navigation__link" href="#1">Graph</a></li>


				</div>

			</ul>

		</nav>
	</div>
	<div class="col-md-9 section1">

		<div class="page-section" id="1">
			<h3 class="text-center">Background</h3>


			<canvas id="myChart" width="400" height="300"></canvas>

		</div>
		<script>


			const ctx = document.getElementById('myChart').getContext('2d');
			const myChart = new Chart(ctx, {
				type: 'bar',
				data: {
					labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],

					datasets: [{
						label: '# of Votes',
						data: [15, 5, 3, 5, 2, 3],
						backgroundColor: [
							'rgba(255, 99, 132, 0.2)',
							'rgba(54, 162, 235, 0.2)',
							'rgba(255, 206, 86, 0.2)',
							'rgba(75, 192, 192, 0.2)',
							'rgba(153, 102, 255, 0.2)',
							'rgba(255, 159, 64, 0.2)'
						],
						borderColor: [
							'rgba(255, 99, 132, 1)',
							'rgba(54, 162, 235, 1)',
							'rgba(255, 206, 86, 1)',
							'rgba(75, 192, 192, 1)',
							'rgba(153, 102, 255, 1)',
							'rgba(255, 159, 64, 1)'
						],
						borderWidth: 1
					}]
				},
				options: {
					scales: {
						y: {
							beginAtZero: true
						}
					}
				}
			});


		</script>

	</div>












</div>

</div>









{% endblock %}

{% block js %}
<script>

	$(document).ready(function () {
		$('a[href*=#]').bind('click', function (e) {
			e.preventDefault(); // prevent hard jump, the default behavior

			var target = $(this).attr("href"); // Set the target as variable

			// perform animated scrolling by getting top-position of target-element and set it as scroll target
			$('html, body').stop().animate({
				scrollTop: $(target).offset().top
			}, 600, function () {
				location.hash = target; //attach the hash (#jumptarget) to the pageurl
			});

			return false;
		});
	});

	$(window).scroll(function () {
		var scrollDistance = $(window).scrollTop();

		// Show/hide menu on scroll
		//if (scrollDistance >= 850) {
		//		$('nav').fadeIn("fast");
		//} else {
		//		$('nav').fadeOut("fast");
		//}

		// Assign active class to nav links while scolling
		$('.page-section').each(function (i) {
			if ($(this).position().top <= scrollDistance) {
				$('.navigation a.active').removeClass('active');
				$('.navigation a').eq(i).addClass('active');
			}
		});
	}).scroll();

</script>


{% endblock %}

agmp_app/templates/outreach.html
{% extends 'mainLayout.html' %}
{% block title %}About{% endblock %}
{% block content %}
{% load static %}
<h3 class="text-center">Outreach</h3>

<h4>Events and workshops</h4>
The following page contains a list of upcoming events and workshops relevant to pharmacogenomics, and genomics and precision medicine.

No events yet added

{% endblock %}

agmp_app/templates/search_list_template.html
{% extends "mainLayout.html" %}
{% load static %}


{% block banner %}


{% include 'partials/banner_search.html' %}

{% endblock %}
{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Searching Page</title>


<style>
.placeholder::placeholder {
  color: #444 !important;
}

.placeholder::-webkit-input-placeholder {
  color: #444 !important;
}

.placeholder::-moz-placeholder {
  color: #444 !important;
}

.placeholder:-ms-input-placeholder {
  color: #444 !important;
}

</style>
 <!-- Include jQuery library -->
 <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

 <script>
 $(document).ready(function () {
     // Function to handle form submission
     $('#search-form').on('submit', function (e) {
         e.preventDefault(); // Prevent default form submission

         // Get the search query from the input field
         var searchQuery = $('#id_search_query').val();

         // Get the selected model from the radio buttons
         var modelSelection = $('input[name=model_selection]:checked').val();

         // Show loading message
         $('#results-list').html('Loading...');

         // Make an AJAX request to the backend
         $.ajax({
             type: 'GET',
             url: '{% url "search_view" %}',
             data: {
                 search_query: searchQuery,
                 model_selection: modelSelection
             },
             success: function (data) {
                 // Extract and update only the #results-list from the received data
                 var updatedResults = $(data).find('#results-list').html();
                 $('#results-list').html(updatedResults);
             },
             error: function (error) {
                 console.log('Error:', error);
                 $('#results-list').html('Error fetching data, try again.');
             }
         });
     });



 // Function to update input field placeholder based on selected option
 $('input[name=model_selection]').on('change', function() {
        var selectedOption = $(this).val();
        var inputField = $('#id_search_query');
        var placeholder = '';

        switch(selectedOption) {
            case 'variantagmp':
                placeholder = 'Enter Variant ID (e.g. rs123456)';
                break;
            case 'geneagmp':
                placeholder = 'Enter Gene name (e.g. UGT2B7)';
                break;
            case 'drugagmp':
                placeholder = 'Enter Drug name (e.g. Carbamazepine)';
                break;
            case 'disease':
                placeholder = 'Enter Phenotype (e.g. Diabetes)';
                break;
        }

        inputField.attr('placeholder', placeholder);
    });










 });
 </script>
</head>
<body>
 <div id="origin-page">
     <div class="center_form_contents">
     <form id="search-form">
        
         <div>
             <label><h5><b>{{ form.model_selection.label }}<h5></b></label>
             <ul id="id_model_selection">
             <li>
                 <input type="radio" name="{{ form.model_selection.html_name }}" value="variantagmp" id="id_model_selection_0">
                 Variant<label for="id_model_selection_1" id ="id_model_selection_variant"> &#160; &#160; &#160; &#160; &#160;</label>
             </li>
             <li>
                 <input type="radio" name="{{ form.model_selection.html_name }}" value="geneagmp" id="id_model_selection_1">
                Gene <label for="id_model_selection_1" id ="id_model_selection_gene"> &#160; &#160; &#160; &#160; &#160;</label>
             </li>
             <li>
                 <input type="radio" name="{{ form.model_selection.html_name }}" value="drugagmp" id="id_model_selection_2">
                Drug <label for="id_model_selection_2" id ="id_model_selection_drug"> &#160; &#160; &#160; &#160; &#160;</label>
             </li>
             <li>
                 <input type="radio" name="{{ form.model_selection.html_name }}" value="disease" id="id_model_selection_3">
                 Phenotype<label for="id_model_selection_3" id="id_model_selection_disease"> &#160; &#160; &#160; &#160; &#160;</label>
             </li>
             </ul>
         </div>
         <div>
             <input class="placeholder mb+2" type="text" name="{{ form.search_query.html_name }}" value="" id="{{ form.search_query.id_for_label }}" maxlength="100">
         </div>
         <button type="submit" class="btn btn-sm btn-outline-primary rounded">Search</button>
     </form>
     </div>
 </div>

 <div class="">
     <ul id="results-list">
         <!-- Results will be dynamically updated here -->
         {% if model_selection == "variantagmp" %}
             {% for result in results %}
                 <b>Variant ID: </b>{{ result.rs_id}}<br>
                 <b>Gene:</b> {{result.geneagmp__gene_id}}<br>
                 <b>Chromosome: </b>{{result.geneagmp__chromosome}}<br>
                 <a href="{% url 'Var_Drug_Assoc' result.rs_id %}">Variant-Drug Associations </a> <br>
                 <a href="{% url 'Variant_Disease_Assoc' result.rs_id %}">Variant-Phenotype Associations </a><br>
                 <hr>
             {% empty %}
                 <p class="text-center" >No results found.</p>
             {% endfor %} 
         {% elif model_selection == "geneagmp" %}
             {% for result in results %}
                 <b>Gene: </b>{{ result.gene_id}}<br>
                 <b>Chromosome: </b>{{result.chromosome}}<br>
                 <a href="{% url 'PhamacogeneDrugAssoc' result.gene_id %}">Gene Associations </a> <br><hr>
             {% empty %}
                 <p class="text-center">No results found.</p>
             {% endfor %}   
         {% elif model_selection == "drugagmp" %}
             {% for result in results %}
                 <b>Drug Name: </b>{{result.drug_name}}<br>
                 <b>Drug Bank ID: </b><a href="https://go.drugbank.com/drugs/{{result.drug_bank_id}}">{{result.drug_bank_id}}</a>
                 <br>
                 <b>State: </b>{{result.state}}<br>
                 <a href="{% url 'VariantDrugAssociation' result.drug_id %}">Variant-Drug Associations</a><br>  
                 <hr>
             {% empty %}
                 <p class="text-center">No results found.</p>
             {% endfor %}   
         {% elif model_selection == "disease" %}
             {% for result in results %}
                 <b>Phenotype:</b> {{result.phenotypeagmp__name}}<br>
                 <a href="{% url 'DiseaseVariant' result.phenotypeagmp__name %}">Variant-Phenotype Associations</a><br><hr> 
             {% empty %}
                 <p class="text-center">No results found.</p>
             {% endfor %}  
         {% endif %}
     </ul>
 </div>
<!-- </body> -->
{% endblock %}